// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DestinyClanData {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox tbSearch;
		
		protected System.Web.UI.WebControls.Button btnSearch;
		
		protected System.Web.UI.WebControls.Button btnSearchClan;
		
		protected System.Web.UI.WebControls.ListView ListView1;
		
		protected System.Web.UI.WebControls.Image Image1;
		
		protected System.Web.UI.WebControls.Label lblUser;
		
		protected System.Web.UI.WebControls.Label lblCharacterClass;
		
		protected System.Web.UI.WebControls.Label lblPowerLevel;
		
		protected System.Web.UI.WebControls.Label lblDataLastPlayed;
		
		protected System.Web.UI.WebControls.Label lblCurrentActivity;
		
		protected System.Web.UI.WebControls.Label lblCurrentActivityDescription;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl listViewLayout;
		
		protected System.Web.UI.WebControls.PlaceHolder itemPlaceholder;
	}
}
